const express = require("express");
const cors = require("cors");
const morgan = require("morgan");
require("dotenv").config();

const { initPool } = require("./config/db");
const app = express();
const tarjetaclienteroutes = require("./routes/tarjetacliente.routes");
const uploadRoutes = require('./routes/upload.routes');

app.use(cors());
app.use(express.json());
app.use(morgan("dev"));

// ── Rutas ──────────────────────────────────────────────────
app.use("/api/abastecimientos", require("./routes/abastecimiento.routes"));
app.use("/api/campanas-marketing", require("./routes/campana_marketing.routes"));
app.use("/api/cargos", require("./routes/cargo.routes"));
app.use("/api/carritos", require("./routes/carrito.routes"));
app.use("/api/carritos-detalle", require("./routes/carrito_detalle.routes"));
app.use("/api/categorias", require("./routes/categoria.routes"));
app.use("/api/clientes", require("./routes/cliente.routes"));
app.use("/api/condiciones-pago", require("./routes/condicion_pago.routes"));
app.use("/api/consumos-materia-prima", require("./routes/consumo_materia_prima.routes"));
app.use("/api/contratos-proveedor", require("./routes/contrato_proveedor.routes"));
app.use("/api/control-calidad", require("./routes/control_calidad.routes"));
app.use("/api/cuentas-pagar-proveedor", require("./routes/cuenta_pagar_proveedor.routes"));
app.use("/api/cuotas-pago", require("./routes/cuotas_pago.routes"));
app.use("/api/cupones", require("./routes/cupon.routes"));
app.use("/api/departamentos", require("./routes/departamento.routes"));
app.use("/api/devoluciones", require("./routes/devolucion.routes"));
app.use("/api/empleados", require("./routes/empleado.routes"));
app.use("/api/envios", require("./routes/envio.routes"));
app.use("/api/estados-envio", require("./routes/estado_envio.routes"));
app.use("/api/estados-orden", require("./routes/estado_orden.routes"));
app.use("/api/estados-orden-compra", require("./routes/estado_orden_compra.routes"));
app.use("/api/estados-produccion", require("./routes/estado_produccion.routes"));
app.use("/api/evaluaciones", require("./routes/evaluacion.routes"));
app.use("/api/expedientes-empleado", require("./routes/expediente_empleado.routes"));
app.use("/api/expedientes-proveedor", require("./routes/expediente_proveedor.routes"));
app.use("/api/facturas", require("./routes/factura.routes"));
app.use("/api/facturas-detalle", require("./routes/factura_detalle.routes"));
app.use("/api/faqs", require("./routes/faq.routes"));
app.use("/api/herramientas", require("./routes/herramienta.routes"));
app.use("/api/historial-cambio-contrasena", require("./routes/historial_cambio_contrasena.routes"));
app.use("/api/historial-compra", require("./routes/historial_compra.routes"));
app.use("/api/historial-laboral", require("./routes/historial_laboral.routes"));
app.use("/api/historial-promocion", require("./routes/historial_promocion.routes"));
app.use("/api/incidentes-laborales", require("./routes/incidente_laboral.routes"));
app.use("/api/inventario-materia-prima", require("./routes/inventario_materia_prima.routes"));
app.use("/api/inventario-producto", require("./routes/inventario_producto.routes"));
app.use("/api/listas-deseos", require("./routes/lista_deseos.routes"));
app.use("/api/listas-materiales", require("./routes/lista_materiales.routes"));
app.use("/api/listas-materiales-detalle", require("./routes/lista_materiales_detalle.routes"));
app.use("/api/mantenimiento-herramientas", require("./routes/mantenimiento_herramienta.routes"));
app.use("/api/materias-primas", require("./routes/materia_prima.routes"));
app.use("/api/metodos-pago", require("./routes/metodo_pago.routes"));
app.use("/api/movimientos-inventario", require("./routes/movimiento_inventario.routes"));
app.use("/api/movimientos-materia-prima", require("./routes/movimiento_materia_prima.routes"));
app.use("/api/nominas", require("./routes/nomina.routes"));
app.use("/api/nominas-detalle", require("./routes/nomina_detalle.routes"));
app.use("/api/ordenes-compra", require("./routes/orden_compra.routes"));
app.use("/api/ordenes-compra-detalle", require("./routes/orden_compra_detalle.routes"));
app.use("/api/ordenes-produccion", require("./routes/orden_produccion.routes"));
app.use("/api/ordenes-produccion-tareas", require("./routes/orden_produccion_tarea.routes"));
app.use("/api/ordenes-venta", require("./routes/orden_venta.routes"));
app.use("/api/ordenes-venta-detalle", require("./routes/orden_venta_detalle.routes"));
app.use("/api/pagos", require("./routes/pago.routes"));
app.use("/api/pagos-proveedor", require("./routes/pago_proveedor.routes"));
app.use("/api/permisos", require("./routes/permiso.routes"));
app.use("/api/planes-produccion", require("./routes/plan_produccion.routes"));
app.use("/api/politicas-envio", require("./routes/politica_envio.routes"));
app.use("/api/precios-historico", require("./routes/precio_historico.routes"));
app.use("/api/preferencias-cliente", require("./routes/preferencia_cliente.routes"));
app.use("/api/produccion-resultados", require("./routes/produccion_resultados.routes"));
app.use("/api/productos", require("./routes/producto.routes"));
app.use("/api/promociones", require("./routes/promocion.routes"));
app.use("/api/promociones-producto", require("./routes/promocion_producto.routes"));
app.use("/api/proveedores", require("./routes/proveedor.routes"));
app.use("/api/recepciones-material", require("./routes/recepcion_material.routes"));
app.use("/api/reglas-envio-gratis", require("./routes/regla_envio_gratis.routes"));
app.use("/api/reglas-promocion", require("./routes/regla_promocion.routes"));
app.use("/api/resenas-comentarios", require("./routes/resena_comentario.routes"));
app.use("/api/roles", require("./routes/rol.routes"));
app.use("/api/roles-empleado", require("./routes/rol_empleado.routes"));
app.use("/api/roles-permiso", require("./routes/rol_permiso.routes"));
app.use("/api/rutas-entrega", require("./routes/ruta_entrega.routes"));
app.use("/api/seguimiento-envio", require("./routes/seguimiento_envio.routes"));
app.use("/api/sesiones", require("./routes/sesion.routes"));
app.use("/api/tarifas-envio", require("./routes/tarifa_envio.routes"));
app.use("/api/tipos-entrega", require("./routes/tipo_entrega.routes"));
app.use("/api/tipos-promocion", require("./routes/tipo_promocion.routes"));
app.use("/api/unidades-medida", require("./routes/unidad_medida.routes"));
app.use("/api/usuarios", require("./routes/usuario.routes"));
app.use("/api/vehiculos", require("./routes/vehiculo.routes"));
app.use("/api/zonas-envio", require("./routes/zona_envio.routes"));
app.use("/api/tarjetas-cliente", tarjetaclienteroutes);
app.use('/api/upload', uploadRoutes);
// ───────────────────────────────────────────────────────────

app.get("/", (req, res) => res.json({ mensaje: "Backend Alpes Mobile ✅" }));

const PORT = process.env.PORT || 3000;
initPool().then(() => {
  app.listen(PORT, () => console.log(`🚀 Servidor en puerto ${PORT}`));
}).catch(err => { console.error(err); process.exit(1); });

module.exports = app;