const router = require("express").Router();
const ctrl = require("../controllers/seguimiento_envio.controller");
const { authenticateToken } = require('../middleware/auth.middleware');
router.get("/", authenticateToken, ctrl.listar);
router.get("/buscar", authenticateToken, ctrl.buscar);
router.get("/cliente/:cliId", authenticateToken, ctrl.porCliente);
router.get("/:id", authenticateToken, ctrl.obtener);
router.post("/", authenticateToken, ctrl.crear);
router.put("/:id", authenticateToken, ctrl.actualizar);
router.delete("/:id", authenticateToken, ctrl.eliminar);
module.exports = router;
